model_params:
  outpath: './example_output'
  observables:
    macro:
      - 'gdp_pc_pp'
      - 'gni_pc_pp'
      - 'pop'
      - 'gini_index'
      - 'extr_pov_rate'
      - 'soc_pov_rate'
      - 'extr_pov_line'
      - 'soc_pov_line'
      - 'extr_pov_line_adj'
      - 'soc_pov_line_adj'
      - 'name'
      - 'region'
      - 'income_group'
      - 'prepare_scaleup'
      - 'finance_pre'
      - 'borrowing_ability'
      - 'avg_prod_k'
      - 'tau_tax'
      - 'k_priv_share'
      - 'k_household_share'
      - 'owner_occupied_share_of_value_added'
      - 'self_employment'
      - 'real_est_k_to_va_shares_ratio'
      - 'rho'
      - 'income_elasticity_eta'
      - 'dk_ctry'
      - 'fa'
      - 'error_incl'
      - 'error_excl'
      - 'need'
      - 'aid'
    results:
      - 'gdp_pc_pp'
      - 'gni_pc_pp'
      - 'pop'
      - 'gini_index'
      - 'extr_pov_rate'
      - 'soc_pov_rate'
      - 'extr_pov_line'
      - 'soc_pov_line'
      - 'extr_pov_line_adj'
      - 'soc_pov_line_adj'
      - 'name'
      - 'region'
      - 'income_group'
      - 'prepare_scaleup'
      - 'finance_pre'
      - 'borrowing_ability'
      - 'avg_prod_k'
      - 'tau_tax'
      - 'k_priv_share'
      - 'k_household_share'
      - 'owner_occupied_share_of_value_added'
      - 'self_employment'
      - 'real_est_k_to_va_shares_ratio'
      - 'rho'
      - 'income_elasticity_eta'
      - 'average_aid_cost_pc'
      - 'dk'
      - 'dk_tot'
      - 'dw'
      - 'dw_tot'
      - 'dWpc_currency'
      - 'dWtot_currency'
      - 'dc'
      - 'dc_tot'
      - 'risk_to_wellbeing'
      - 'risk_to_consumption'
      - 'risk_to_assets'
      - 'resilience'
    iah:
      - 'fa'
      - 'v_ew'
      - 'income_share'
      - 'transfers'
      - 'liquidity'
      - 'axfin'
      - 'diversified_share'
      - 'n'
      - 'c'
      - 'gamma_SP'
      - 'k'
      - 'dk'
      - 'dk_reco'
      - 'help_needed'
      - 'help_received'
      - 'lambda_h'
      - 'dW_reco'
      - 'dS_reco_PDS'
      - 'dc_short_term'
      - 'dC_max'
      - 'recovery_params'
      - 'dk_pub'
      - 'help_fee'
      - 'reco_fee'
      - 'dc_long_term'
      - 'dW_long_term'
      - 'dc'
      - 'dw'
  run_params:
    verbose: False
  pds_params:
    pds_variant: 'no'
    pds_targeting: 'perfect'
    pds_borrowing_ability: 'unlimited'
    pds_lending_rate: 0.05
    pds_scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    covered_loss_share: 0.4
scenario_params:
  run_params:
    recompute: True
    recompute_hazard_protection: False
    download: False
    verbose: False
    countries: 'all'
    exclude_countries: ['THA']
    hazards: 'all'
    pip_reference_year: 2021
    include_poverty_data: True
    poverty_line: 3.0
    resolution: .2
  macro_params:
    income_elasticity_eta: 1.5
    discount_rate_rho: .06
    axfin_impact: .1
    reduction_vul: .2
    reconstruction_capital: 'self_hous'
    early_warning_file: null
  hazard_params:
    hazard_protection: 'FLOPROS'
    no_exposure_bias: False
    fa_threshold: .99
    zero_rp: 2
  data_params:
    transfers_regression_params:
#      type: 'OLS'
#      specification:
#        .2: 'transfers ~ GDP_{pc} + REM + SOC + UNE + I_{ECA}'
#        .4: 'transfers ~ GDP_{pc} + REM + SOC + UNE'
#        .6: 'transfers ~ GDP_{pc} + REM + SOC + UNE'
#        .8: 'transfers ~ GDP_{pc} + REM + SOC + I_{EAP}'
#        1.: 'transfers ~ GDP_{pc} + REM + SOC + I_{EAP}'
      type: 'LassoCV'
      features: ['GDP_{pc}', 'REM', 'SOC', 'UNE', 'income_group', 'region', 'FSY']
  policy_params:
    scale_self_employment:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_non_diversified_income:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    min_diversified_share:
      parameter: 0
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_income:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_liquidity:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
    scale_exposure:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
      scale_total: False
    scale_vulnerability:
      parameter: 1
      scope: [[0, .2], [.2, .4], [.4, .6], [.6, .8], [.8, 1]]
      scale_total: False
    scale_gini_index:
      parameter: 1
